dataset:
  data_path: data/
  dev_ratio: 0
  has_node_feat: false
  is_overwrite_precompute: false
  is_sample_subgraph: true
  is_save_split: false
  loader_name: GRANData
  name: dia3
  node_order: DFS
  num_fwd_pass: 1
  num_subgraph_batch: 1
  train_ratio: 1
device: cuda:0
exp_dir: exp/GRAN
exp_name: GRANMixtureBernoulli_dia3_2024-Jul-03-17-01-01_24658
gpus:
- 1
model:
  block_size: 1
  dimension_reduce: true
  edge_weight: 1.0
  embedding_dim: 512
  has_attention: true
  hidden_dim: 512
  is_sym: true
  max_num_nodes: 1458
  name: GRANMixtureBernoulli
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 20
  sample_stride: 1
run_id: '24658'
runner: GranRunner
save_dir: exp/GRAN/GRANMixtureBernoulli_dia3_2024-Jul-03-17-01-01_24658
seed: 1234
test:
  batch_size: 1
  better_vis: true
  is_single_plot: false
  is_test_ER: false
  is_vis: true
  num_test_gen: 10
  num_vis: 20
  num_workers: 0
  test_model_dir: snapshot_model
  test_model_name: gran_dia3.pth
  vis_num_row: 5
train:
  batch_size: 1
  display_iter: 10
  is_resume: false
  lr: 0.0001
  lr_decay: 0.1
  lr_decay_epoch:
  - 100000000
  max_epoch: 20000
  momentum: 0.9
  num_workers: 1
  optimizer: Adam
  resume_dir: null
  resume_epoch: 5000
  resume_model: model_snapshot_0005000.pth
  shuffle: true
  snapshot_epoch: 100
  valid_epoch: 50
  wd: 0.0
use_gpu: true
use_horovod: false
